### PR TITLE
V450

### PR DESCRIPTION
**Pull request by stuartpittaway**

### CODE REVIEW

**Comment by N1c084** [comment]
Hi
 there is a new board with Attiny1614?
This chip can help to connect more than 125 modules?

**Comment by stuartpittaway** [comment]
Hi, if you take a look at the code I wrote this 2 years ago for an experimental board I made.  I may try and look at bringing it back based on the non-availability of the tiny841

**Comment by N1c084** [comment]
Sorry , writing too fast😅
It seem the clock of Attiny841 was set to lower frequency , why please ?
Can you explain the limitation of number of modules in series? It is due to
speed of attiny or limited data size on bus or other?
Can we connect several contrôler in parallel operation on same battery with
a master contrôler or add this feature ?

Le ven. 12 août 2022 à 08:40, Stuart Pittaway ***@***.***> a
écrit :

**Comment by stuartpittaway** [comment]
ATTINY841 is running at 2Mhz so it works reliably down at 1.8V.

The limitation of the number of modules is purely down to the communication speed (baud rate) between the ATTINY chips.  
The 841 chip has a poor internal clock frequency, which causes errors in communications.

The V4.40 modules solve this by using an external clock, so can operate at 9600 baud instead of 2400.

**Comment by N1c084** [comment]
thanks
for cells witch normally never go under 2.9V we can set it between 4 and 8MHz
baud rate can also be set higher maybe 4Mhz and 19.2k baudrate can improve nb of modules in an array?

**Comment by stuartpittaway** [comment]
You can certainly try it, but without the external crystal/clock on the ATTINY841 I ran into a lot of problems.

**Comment by N1c084** [comment]
I will order new v440 pcb.
My system was under construction , I will not run before winter.
I will sell my leaf pcb and go to standard v440.
There is new release of hardware planned in few months ? To know if I place
an order now or waiting hardware upgrade?
I will take 200pcb .
Can I change the external quartz for other frequency or better quality
component or the actual is good to try 19.2kHz?
Thanks

Le sam. 13 août 2022 à 13:23, Stuart Pittaway ***@***.***> a
écrit :

**Comment by stuartpittaway** [comment]
The clock speed is reliable with the external clock as specified in the 4.4 design.

I may need to update the PCB soon as it's almost impossible to get the tiny841 chips now.

**Comment by stuartpittaway** [comment]
I'm exploring use of different attiny chips at the moment, but nothing production ready

**Pull request closed without merging**
