### PR TITLE
PYLONTECH ForceH* canbus support

### PR DESCRIPTION
**Pull request by pprasse**
Hi @stuartpittaway,

I implemented PYLONTECH ForceH* CANbus support for diyBMS.
I'm currently testing it with my Goodwe GW25K-ET inverter and a 80S diyBMS setup.

To properly work the inverter needs to be updated to ARM firmware V6, otherwise it will ignore any discharge current settings from CAN bus and limit discharge to 10A.

The usStackDepth changes in xTaskCreate for replyqueue_task and canbus_tx are because I got panics every 1-2 hours and with these settings these panics are gone.

- Patrick

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Great work, I'll take a look.

**Comment by pprasse** [comment]
Hello @stuartpittaway,

do you have any comments yet?

This HV setup is probably not (yet) a common setup for diyBMS, so I could show you my complete setup so you can verify everything works with this pull-rq.

* Patrick

**Comment by stuartpittaway** [comment]
Hi @pprasse.  The code looks good.  Its a shame we can't find others to test this out.

My only real concern is promoting high voltage DC setup's - I've tried to remain below the 50 volt range to keep things "safer" and generally recommend this for DIY purposes.

So if I accept this code, I'm sort of undoing that recommendation.

**Comment by stuartpittaway** [comment]
@pprasse I've decided to merge this into the next release.  Thank you very much for the work.

**Pull request merged**
